# Generated by Django 4.0.6 on 2022-08-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30)),
                ('goods_price', models.IntegerField()),
                ('goods_type', models.CharField(default='all', max_length=30)),
                ('goods_photo', models.CharField(max_length=80)),
            ],
        ),
    ]
