# Generated by Django 4.0.6 on 2022-08-09 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30)),
                ('goods_price', models.IntegerField()),
                ('goods_type', models.CharField(default='all', max_length=30)),
                ('goods_photo', models.CharField(max_length=80)),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.people')),
            ],
        ),
    ]
