# Generated by Django 4.0.6 on 2022-08-10 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_alter_buy_car_g_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_car',
            name='g_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booktest.goods'),
        ),
    ]
