# Generated by Django 4.0.6 on 2022-08-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0007_alter_buy_car_g_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_car',
            name='g_id',
            field=models.IntegerField(),
        ),
    ]
