# Generated by Django 4.0.6 on 2022-08-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0008_alter_buy_car_g_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
    ]
