# Generated by Django 4.0.6 on 2022-08-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0009_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('cityname', models.CharField(default='null', max_length=255)),
                ('type', models.IntegerField(default='null')),
            ],
        ),
    ]
