# Generated by Django 4.0.6 on 2022-08-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0010_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='pid',
            field=models.IntegerField(default='null'),
        ),
    ]
