# Generated by Django 4.0.6 on 2022-08-21 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0011_alter_city_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_phone', models.CharField(default='', max_length=22)),
                ('user_sheng', models.CharField(default='', max_length=60)),
                ('user_shi', models.CharField(default='', max_length=60)),
                ('user_xian', models.CharField(default='', max_length=60)),
                ('user_deAddress', models.CharField(default='', max_length=60)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.people')),
            ],
        ),
    ]
