# Generated by Django 4.0.6 on 2022-08-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0012_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='user_default_address',
            field=models.IntegerField(default=0),
        ),
    ]
