# Generated by Django 4.0.6 on 2022-08-22 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0013_user_address_user_default_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods_intriduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(default='商品暂无介绍信息')),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.goods')),
            ],
        ),
    ]
