# Generated by Django 4.0.6 on 2022-08-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0014_goods_intriduce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='goods_intriduce',
        ),
    ]
