# Generated by Django 4.0.6 on 2022-08-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0015_delete_goods_intriduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='info',
            field=models.TextField(default='商品暂无介绍信息'),
        ),
    ]
