# Generated by Django 4.0.6 on 2022-08-22 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0016_goods_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 11, 36, 55, 828386)),
        ),
    ]
