# Generated by Django 4.0.6 on 2022-08-22 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0017_people_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 11, 57, 14, 931678)),
        ),
    ]
