# Generated by Django 4.0.6 on 2022-08-22 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0018_alter_people_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='time_stamp',
            field=models.FloatField(default=1661141106.7238808),
        ),
        migrations.AlterField(
            model_name='people',
            name='create_time',
            field=models.DateField(default=datetime.date),
        ),
    ]
