# Generated by Django 4.0.6 on 2022-08-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0019_people_time_stamp_alter_people_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='create_time',
        ),
        migrations.AlterField(
            model_name='people',
            name='time_stamp',
            field=models.FloatField(default=1661750756.6367579),
        ),
    ]
