# Generated by Django 4.0.6 on 2022-08-29 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0020_remove_people_create_time_alter_people_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='create_time',
            field=models.DateField(default=datetime.date(2022, 8, 29)),
        ),
        migrations.AlterField(
            model_name='people',
            name='time_stamp',
            field=models.FloatField(default=1661750931.3957276),
        ),
    ]
